### PR TITLE
Fix links to appropriate versions of docs, in preparation for redirec…

### PR DESCRIPTION
**Pull request by stevepiercy**
…ting docs.plone.org to 6.docs.plone.org

- Fix a few other typos

### CODE REVIEW

**Comment by stevepiercy** [comment]
Refs: https://github.com/plone/documentation/pull/1404

**Comment by stevepiercy** [comment]
I'm not sure how to fix the build failure, but here's the error message:

`linkcheck: failed with mkdir is not allowed, use allowlist_externals to allow it`

It works fine locally. `¯\_(ツ)_/¯`

**Review by mauritsvanrees — APPROVED** [review]
LGTM.

You likely use `tox` version 3 locally, which is more forgiving. On gh-actions we will get the recent tox` 4, which give problems like this. Either we should force `pip install "tox<4"` for now, or do something like adding some commands to `allowlist_externals` config options in the `tox.ini` file.

**Comment by stevepiercy** [comment]
I'm in favor of using the latest tox in CI. Should I do that in this PR or a separate one?

**Comment by mauritsvanrees** [comment]
> I'm in favor of using the latest tox in CI. Should I do that in this PR or a separate one?

I don't mind. Your choice. I guess it fails on master as well already.

**Comment by stevepiercy** [comment]
This was fairly straightforward. There was a [renaming of a configuration option in tox](https://tox.wiki/en/latest/changelog.html#deprecations-and-removals-4-0-0rc4). Fix pushed, now waiting to see whether I got all the issues in GHA.

**Comment by stevepiercy** [comment]
Another [tox 4 error](https://github.com/plone/plone.api/actions/runs/3792986432/jobs/6449673822#step:6:37):

```console
ValueError: conflicting factors py37, 5.2 in py37-plone-5.2
  py[37](https://github.com/plone/plone.api/actions/runs/3792986432/jobs/6449673822#step:6:38)-plone-5.2: FAIL code 2 (0.00 seconds)
  evaluation failed :( (0.54 seconds)
```

I looked at the matrix in `env_list`, and noticed that the Pythons had no `.`, but the Plones did. I also noticed an extra `-`. I removed them, and that seemed to resolve the matter locally. Let's see what GHA says.

**Comment by stevepiercy** [comment]
See also this excellent guide [Breaking changes in tox 4](https://tox.wiki/en/latest/faq.html#breaking-changes-in-tox-4). h/t @jugmac00

**Comment by stevepiercy** [comment]
@jenkins-plone-org please run jobs

**Comment by stevepiercy** [comment]
@mauritsvanrees all green on GHA. It can be clumsy to combine two things in a single PR and news item. Please let me know if you would like me to split them apart, and I can do so.

**Comment by mauritsvanrees** [comment]
Thanks!

**Pull request merged**
