### PR TITLE
Add test to demonstrate issue

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by adamcheasley** [comment]
It appears the tests have failed due to the fact that in plone 5, you don't actually get an unauthorized raised. In that case, the function raises an `InvalidParameterError`

**Comment by jaroel** [comment]
I've fixed the actual problem in #264.

**Comment by hvelarde** [comment]
no, the point is a user with Member role is not allowed to create content; as you can see the test passes in other Plone versions but 5.0.

**Comment by hvelarde** [comment]
the issue happens with Dexterity-based content types; test could fail under Plone 4 if we were using plone.app.contenttypes.

**Comment by jaroel** [comment]
Yep, this is because plone.dexterity.content.invokefactory does FTI checks before permission checks.

**Comment by jaroel** [comment]
Please file a bug report with plone.dexterity ;) :+1:

**Comment by hvelarde** [comment]
@jaroel why don't we merge the test?

**Comment by jaroel** [comment]
We'll need to add a conditional dependency to plone.dexterity >= 2.3.3

**Comment by jaroel** [comment]
I don't see how I can do this.
We either have plone.dexterity, or we don't. This needs to be in the KGS.

**Pull request closed without merging**
