### PR TITLE
Report non existing permissions

### LINKED ISSUE #515: Warn if the permission does not exist
I was doing some tests using `api.user.has_permission` and the test was failing 💥 but of course I should be right 🤣 

Turns out that I have a permission:

```xml
  <permission
    id="der.freitag.my-permission"
    title="der.freitag: Cool stuff"
    />
```

And my api call was:

```python
api.user.has_permission(
    'der.freitag.my-permission',
    obj=self.portal.autoren[user1['USER_ID']])
)
```

But, actually this is indeed wrong, the right call is:

```python
api.user.has_permission(
    'der.freitag: Cool stuff',
    obj=self.portal.autoren[user1['USER_ID']])
)
```

i.e. one has to use the `title` of the permission, not the `id`! 🤦🏾 

It would be nice if either `plone.api` could use either of them, or otherwise warn the user if the permission does not exist at all.

I can hardly think of any valid/reasonable use case where you don't want the permission that you are checking to __not__ exist.

As a first step, mentioning it on the documentation it would be helpful ✨

### PR DESCRIPTION
**Pull request by gforcada**
Closes #515

### CODE REVIEW

**Comment by davisagli** [comment]
There's a failing test.

**Comment by gforcada** [comment]
This is using #512 to be able to test properly with `tox`, so let's merge that one first 🍀

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Review by davisagli — APPROVED** [review]

**Review by ale-rt — APPROVED** [review]
I like the idea!

**Comment by jaroel** [comment]
Closes #372

**Comment by jaroel** [comment]
Addresses #401

**Pull request merged**
