### PR TITLE
No need for unittest2

### PR DESCRIPTION
**Pull request by gforcada**
Since python 2.7 unittest2 was already merged with unittest.

### CODE REVIEW

**Comment by jensens** [comment]
@gforcada please add a line to the changelog

tests: http://jenkins.plone.org/job/pull-request-5.0/308/

**Comment by mauritsvanrees** [comment]
Isn't plone.api master still meant for older versions of Plone too?  Plone 4.2 and 4.3 still support Python 2.6, so plone.api should too. Of course unittest2 can then be added conditionally to the install_requires, but the imports would need to stay the same if I see it correctly.

**Comment by mauritsvanrees** [comment]
We test master on Travis with Plone 4.2 and Python 2.6.

Oh, but on this pull request Travis passes... Was unittest2 merged into Python 2.6 as well maybe?

**Comment by gforcada** [comment]
@vangheem good points, and no idea about why it passes... if at all I would prefer to leave the code cleaner than more involved just for a stupid dependency, so let's not merge it until we are sure we can do so.

**Comment by mauritsvanrees** [comment]
i guess we are simply not using any unittest2 features. That would explain it.

**Comment by gforcada** [comment]
Then it is safe to merge... let me resolve the conflicts.

**Comment by mauritsvanrees** [comment]
Agreed.

**Pull request merged**
