### PR TITLE
Use Read the Docs for pull request previews

### PR DESCRIPTION
**Pull request by stevepiercy**
This pull request replaces the Netlify pull request preview build which supports only Python 3.8.

### CODE REVIEW

**Comment by stevepiercy** [comment]
w00t! Success!

https://ploneapi--545.org.readthedocs.build/

Who else should I add to the [Read the Docs plone.api project](https://app.readthedocs.org/projects/ploneapi/) as an Admin? I should not be the only person.

**Comment by davisagli** [comment]
@stevepiercy You can add me, and I'd suggest @ericof as well.

**Review by davisagli — APPROVED** [review]

**Comment by stevepiercy** [comment]
Ack! It wasn't ready! Sorry, I should have set this to draft.

**Comment by davisagli** [comment]
@stevepiercy Sorry...but what wasn't ready? I saw your link in https://github.com/plone/plone.api/pull/545#issuecomment-2548239748 and took that as an indication that it was working.

**Comment by stevepiercy** [comment]
I have to remove some noise and Netlify.

**Comment by stevepiercy** [comment]
Also I wanted to come up with a more elegant tox environment, other than copy-paste and tweak, to make it more maintainable.

**Pull request merged**
