### PR TITLE
implement portal.translate

### PR DESCRIPTION
**Pull request by ebrehault**
as discussed in #291

### CODE REVIEW

**Comment by jcbrand** [comment]
In the comments, "negociated" must be spelled "negotiated".

**Comment by thet** [comment]
@gforcada can't the author of the qa check be changed to a bot author instead your own account?

**Comment by gforcada** [comment]
@thet I already asked for it, and @tisto hopefully does so in the following days. See https://github.com/plone/jenkins.plone.org/issues/146

**Comment by gforcada** [comment]
@ebrehault I took the liberty to rebase your branch and merge your commits into a single one

**Comment by ebrehault** [comment]
@gforcada you did well, thank you. My commits are always messy, I should improve that.

**Comment by gforcada** [comment]
@ebrehault although you most probably know already everything: http://docs.plone.org/develop/coredev/docs/git.html

**Comment by ebrehault** [comment]
@gforcada thank you for the link :), that was helpful. I have applied those guidelines to this PR: https://github.com/plone/Products.CMFPlone/pull/1300/commits

**Pull request merged**
