### PR TITLE
Re-add doctests after switch from restructuredText to MyST markdown

### PR DESCRIPTION
**Pull request by ksuess**
Run all tests and checks:
tox

List all tests and checks run by tox:
tox -l

### CODE REVIEW

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Comment by stevepiercy** [comment]
@ksuess from the Jenkins console:

https://jenkins.plone.org/job/pull-request-6.0-3.9/1274/console

```
Installing test.
Version and requirements information containing manuel:
  [versions] constraint on manuel: 1.10.1
  Requirement of plone.subrequest[test]==1.9.3: manuel
  Requirement of plone.api[test]: manuel>=1.11.2
  Requirement of manuel: six
  Requirement of manuel: setuptools
While:
  Installing test.
Error: The requirement ('manuel>=1.11.2') is not allowed by your [versions] constraint (1.10.1)
Build step 'Virtualenv Builder' marked build as failure
```

That is weird. Where does v1.10.1 come from? Is this a cache issue?

**Review by mauritsvanrees — APPROVED** [review]
Thanks a lot!

**Comment by mauritsvanrees** [comment]
@stevepiercy That error is because manuel is pinned to an older version in the coredev buildout. Katja and I made a [PR](https://github.com/plone/buildout.coredev/pull/796) to update the pin and use the branch from this `plone.api` PR.
It is green now. Next steps:

1. I change the version pin in coredev, and close the other PR.
2. I merge this PR.

**Pull request merged**
