### PR TITLE
Fix regex asserts

### PR DESCRIPTION
**Pull request by gforcada**
That's part of https://github.com/plone/Products.CMFPlone/issues/3852 effort

### CODE REVIEW

**Comment by jensens** [comment]
Why are there still tests for 5.2? Should we run `plone.meta` on this before merging here?

**Comment by mauritsvanrees** [comment]
Coredev 5.2 uses branch 1.x, so from that point of view it is fine to drop 5.2 support.

**Comment by gforcada** [comment]
@jensens @mauritsvanrees on #519 I fixed the plone/python versions being tested, so that PRs can actually pass 👍🏾 

This one should work now 🍀

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
@jensens `plone/meta` is on #509 I will rebase it and there were a few things that needed discussion, or that I was not 100% sure on how to handle them

**Comment by gforcada** [comment]
The failing 3.12 job is expected, as we are missing some version pins from https://github.com/plone/buildout.coredev/pull/890 which in turn fails on 3.12 because it's missing the fixes here 🥚 🐔

**Comment by gforcada** [comment]
Merging as it works on 6.0/1 and it is needed for Python 3.12 👍🏾

**Pull request merged**
