### PR TITLE
Fixed test failures on Python 3 with Products.MailHost 4.10.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Part of https://github.com/plone/Products.CMFPlone/issues/3178
Needs to be tested and merged together with other PRs.

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@jensens Note that the tests could very well fail with the older Products.MailHost. That is why I did not start Jenkins jobs.
I tested all branches together in https://github.com/plone/buildout.coredev/pull/679 and now that PR is finally green. So for me it would be fine to merge all branches from that PR.

Well, for `plone.api` still needs to work on Plone 5.1 as well, so it is good to run Jenkins for that. 

Theoretically I could change the PRs to work with both old and new Products.MailHost. That would make it easier to review, approve and merge single PRs, but means more work for me.

Note that all PRs only have changes in the tests, not in production code.

**Comment by jensens** [comment]
> Well, for plone.api still needs to work on Plone 5.1 as well, so it is good to run Jenkins for that.

right, that was my idea too

**Comment by mauritsvanrees** [comment]
5.1 (and 4.3) passed successfully.
As expected, the Python jobs fail with the older MailHost.

**Pull request merged**
