### PR TITLE
Add local TOCS to main docs pages

### LINKED ISSUE #90: Add .. contents:: :local: to all Sphinx pages
This will generate in-page quick links TOC in Sphinx

      .. contents:: :local: 

I suggest adding it after the heading of each plone.api manual page.

### PR DESCRIPTION
**Pull request by jaroel**
Fixes #90

### CODE REVIEW

**Comment by adamcheasley** [comment]
It appears that the tests failed here, but I believe it was just due to a network timeout. I think it's probably safe to merge this. Can someone else confirm?

**Comment by tisto** [comment]
I just restarted the travis build.

**Comment by gforcada** [comment]
Any reason not to add it also to ``content.rst``?

**Comment by jaroel** [comment]
@gforcada missed it.

**Comment by jaroel** [comment]
Please review.

**Comment by gforcada** [comment]
Merged!

**Pull request merged**
