### PR TITLE
Add section on squashing commits into the conventions

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by hvelarde** [comment]
this probably needs a better redaction or examples; please feel free to comment and improve.

**Comment by adamcheasley** [comment]
Just made a small grammar correction, but otherwise looks good. I don't think we need too many examples, as a contributor should have at least some git knowledge. Maybe we could add a link to the git documentation?

**Comment by hvelarde** [comment]
talking on squashing... I already squashed you corrections

**Comment by gforcada** [comment]
Maybe a link to https://github.com/plone/buildout.coredev/blob/5.0/docs/git.rst (wherever that's published)?

**Pull request merged**
