### PR TITLE
No longer mark Plone 4.0 and Plone 4.1 as supported.

### LINKED ISSUE #237: API not compatible with Plone 4.1
There are some tests failing: https://travis-ci.org/plone/plone.api/jobs/64567653

### PR DESCRIPTION
**Pull request by jaroel**
Closes #237 and #240

### CODE REVIEW

**Comment by jaroel** [comment]
Both aren't tested and the buildout don't work.
plone.api could never have worked in Plone 4.0 because of 'from zope.component.hooks import getSite' in portal.py

Also: I really don't care about 4.0 and 4.0.

**Comment by hvelarde** [comment]
nobody else cares?

**Comment by jaroel** [comment]
Thanks! :)

**Comment by jaroel** [comment]
This closes #240 too.

**Pull request merged**
