### PR TITLE
Make request arguments optional.

### PR DESCRIPTION
**Pull request by jaroel**
Implements #215

### CODE REVIEW

**Comment by jaroel** [comment]
Please review.

**Comment by zupo** [comment]
Ugh, I think we had it like this already but then people complained that we should not use thread locals / global request. Would like to hear more opinions on this one before we merge it ...

**Comment by adamcheasley** [comment]
IMO as long as we still have the option to pass in the request, then this should be fine.

**Comment by jaroel** [comment]
That's still there. I just don't want to have to pass request, if zope.globalrequest.getRequest would do :)

**Comment by jaroel** [comment]
@adamcheasley Please merge if it's acceptable.

**Comment by zupo** [comment]
@davisagli can you please take a look at this one? I'm sure there were people against using the global request and you name pops up in my head as one such potential person.

**Comment by zupo** [comment]
For what is worth, the Pyramid folks are *strongly* against using global requests: http://docs.pylonsproject.org/projects/pyramid/en/1.0-branch/narr/threadlocals.html

"You probably should almost never use the get_current_request() or get_current_registry() functions, except perhaps in tests. "

**Comment by davisagli** [comment]
There's no doubt that avoiding thread locals is cleaner. The main arguments against them are:
1. They assume your code is always going to be run by a threaded server (probably true for zope, but not necessarily for people experimenting with async approaches) with only one request being served per thread.
2. They're not re-entrant (so, for example, one module being published by the Zope publisher can't call to publish a subrequest without fiddling with the thread locals to make sure they're restored afterward).
3. They make your code harder to test and run outside of the web framework, because you have to remember to set up and tear down the thread locals.

On the flip side, it's a nicer experience for the developer if they don't have to pass the request around everywhere.

What if we made a helper like this:

    from Testing.makerequest import makerequest
    from zope.globalrequest import getRequest
    import Zope2
    def get_request():
        request = getRequest()
        if request is None:
            request = makerequest(Zope2.app()).REQUEST
        return request
and use that in plone.api when it wants an implicit request? That way at least it doesn't break in tests and zopectl run scripts, addressing objection 2 above. (Might need to add some marker interfaces to the request from makerequest.)

But I think for the cases shown here, get_view and show_message, it's probably better to be explicit about it, since they are both actions that don't make much sense without a request. Actually in the case of show_message I wish it was just a method on the request so I didn't have to import anything, even from plone.api.

**Comment by jaroel** [comment]
Fair enough :)

**Pull request closed without merging**
