### PR TITLE
Handle automatic transitions

### PR DESCRIPTION
**Pull request by gforcada**
If content.transition is called with a to_state parameter,
a list of transitions that make possible to move from the object original
state to the final desired state is compiled with ``_wf_transitions_for``.

If that list of transitions contain any automatic transition and is triggered
the iteration over that list of transitions will be broken as the
automatic transition will have already happened.

This commit handles this case.

Again, just like #306 making a test for this seems not trivial at all :-/

Is there a way to create workflows on the fly easily?

### CODE REVIEW

**Comment by gforcada** [comment]
Anyone up for reviewing/merging? :-)

**Comment by hvelarde** [comment]
we need a rebase here

**Comment by gforcada** [comment]
@adamcheasley or anyone else, any chances to get this merged?

**Comment by gforcada** [comment]
@hvelarde thanks!

**Pull request merged**
