### PR TITLE
Create relation only if there is no existing one with same …

### PR DESCRIPTION
**Pull request by ksuess**
source, target, relationname.
But mark source as modified.

### CODE REVIEW

**Review by stevepiercy — COMMENTED** [review]
It would be good to add a sentence or two to the documentation with this detail. I've also modified an existing sentence. I'm not sure if the new suggestion is 100% correct

https://6.docs.plone.org/plone.api/relation.html#create-relation

```
If the relation is based on a `RelationChoice` or `RelationList` field on the source object, then the value of that field is created or updated accordingly.

When calling {meth}`create()`, if a relation with the same `source`, `target`, or `relationship` does not exist, then it creates the relation and marks the `source` as modified. However if the relation exists, then [something else happens or doesn't].
```

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Review by pbauer — APPROVED** [review]

**Comment by ksuess** [comment]
@mauritsvanrees  May this be released, please. It's needed for administering relations in the upcoming relations control panel https://github.com/plone/volto/pull/3382

**Comment by mauritsvanrees** [comment]
Sure.  I have released `plone.api` 2.0.3.

**Comment by ksuess** [comment]
> Sure. I have released `plone.api` 2.0.3.

Thank you!

**Pull request merged**
