### PR TITLE
Add autopep8 to the convention docs

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Plus run it on our own code for good measure.

### CODE REVIEW

**Comment by jensens** [comment]
After this stucks a while I ping the doc-heros @polyester and @svx for a comment.

My opinion: I'am not 100% sure if the conventions document is the right place for tool explanations.
I'am totally +1 to have this documented in the plone docs.

**Comment by mauritsvanrees** [comment]
I have put it in the conventions document, because this is a tool that assist in keeping to one of the conventions.

But anywhere in the Plone docs is fine with me. Or only a link to https://pypi.python.org/pypi/autopep8

**Comment by polyester** [comment]
as long as it's clear you run this *only* on .py files, and **never** on .rst files. Can't hurt repeating that.

There's no real 'optimal' place in the docs yet, but we point to the plone.api conventions elsewhere as well as Good Practice & Things You Should Do, so it's fine here.

**Comment by jensens** [comment]
travis fails for 5.0 after merge, but seems unrelated to this merge, see #281

**Pull request merged**
